server:
  port: 9090
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.198.191.54:3306/interView?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: Hxc980203@
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hxc.interView.entity